version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5434:5432
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always